project:
  name: @project.name@
  version: @project.version@

spring:
  application:
    name: @project.name@
    version: @project.version@
  data:
    mongodb:
      uri: mongodb://admin:admin%40123@ds239936.mlab.com:39936/CloudFoundry_d3qg4ucf_fcu2gboc

server:
  port: 8980
  schema: http
  hostname: localhost

# enable all actuator endpoints
management:
  endpoints:
    web:
      exposure:
        include: "*"

# if you'd like to expose shutdown:
# management.endpoint.shutdown.enabled=true

eureka:
  instance:
    hostname: ${server.hostname}
    port: 8999
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${server.schema}://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
