project:
  name: @project.name@
  version: @project.version@

spring:
  application:
    name: @project.name@
    version: @project.version@

# proxy routing set-up
zuul:
  #Service will be mapped under the /api URI
  prefix: /api
  routes:
    order:
      path: /svc-order/**
      serviceId: ORDER
    customer:
      path: /svc-customer/**
      serviceId: CUSTOMER

# enable all actuator endpoints
management:
  endpoints:
    web:
      exposure:
        include: "*"

# if you'd like to expose shutdown:
# management.endpoint.shutdown.enabled=true

eureka:
  instance:
    hostname: ${server.hostname}
    port: 8999
    statusPageUrlPath: /actuator/info
    healthCheckUrlPath: /actuator/health
    homePageUrl: /
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${server.schema}://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
